=== jrsoftware/issrc/ISHelp/isetup.dtd
<!--
  Inno Setup
  Copyright (C) 1997-2026 Jordan Russell
  Portions by Martijn Laan
  For conditions of distribution and use, see LICENSE.TXT.

  Document Type Definition for isetup.xml
-->

<!ENTITY nbsp   "&#x00A0;">
<!ENTITY copy   "&#x00A9;">
<!ENTITY times  "&#x00D7;">
<!ENTITY divide "&#x00F7;">
<!ENTITY ndash  "&#x2013;">
<!ENTITY mdash  "&#x2014;">
<!ENTITY rarr   "&#x2192;">
<!ENTITY approx "&#x2248;">
<!ENTITY le     "&#x2264;">
<!ENTITY ge     "&#x2265;">

<!ENTITY % _inlineExceptLink "b | br | i | sup | tt | u">
<!ENTITY % _inline "%_inlineExceptLink; | link | extlink | img | a | anchorlink | sd">
<!ENTITY % _block "p | heading | pre | precode | example | examples | indent | ul | ol | dl | paramlist | flaglist | table">

<!ENTITY % Inline "(#PCDATA | %_inline;)*">
<!ENTITY % InlineExceptLink "(#PCDATA | %_inlineExceptLink;)*">
<!ENTITY % Block "(%_block;)*">
<!ENTITY % InlineOrBlock "(#PCDATA | %_inline; | %_block;)*">

<!ELEMENT ishelp (contents?, (topic | setuptopic)*)>
<!ATTLIST ishelp version CDATA #REQUIRED>

<!ELEMENT contents ((contentstopic | contentsheading)*)>
<!ELEMENT contentstopic EMPTY>
<!ATTLIST contentstopic title CDATA #REQUIRED topic CDATA #REQUIRED>
<!ELEMENT contentsheading ((contentstopic | contentsheading)*)>
<!ATTLIST contentsheading title CDATA #REQUIRED>

<!ELEMENT topic (keyword*, body)>
<!ATTLIST topic name CDATA #REQUIRED title CDATA #REQUIRED>
<!ELEMENT keyword EMPTY>
<!ATTLIST keyword value CDATA #REQUIRED anchor CDATA #IMPLIED>

<!ELEMENT setuptopic (keyword*, setupformat?, setupvalid?, setupdefault?, body)>
<!ATTLIST setuptopic directive CDATA #REQUIRED title CDATA #IMPLIED>
<!ELEMENT setupformat %Inline;>
<!ELEMENT setupvalid %Inline;>
<!ELEMENT setupdefault %Inline;> 

<!ELEMENT body %Block;>

<!-- Inline elements -->

<!ELEMENT b %Inline;>
<!ELEMENT br EMPTY>
<!ELEMENT i %Inline;>
<!ELEMENT sup %Inline;>
<!ELEMENT tt %Inline;>
<!ELEMENT u %Inline;>
<!ELEMENT link %InlineExceptLink;>
<!ATTLIST link topic CDATA #REQUIRED anchor CDATA #IMPLIED>
<!ELEMENT extlink %InlineExceptLink;>
<!ATTLIST extlink href CDATA #REQUIRED>
<!ELEMENT img %InlineExceptLink;>
<!ATTLIST img src CDATA #REQUIRED>
<!ELEMENT a %InlineExceptLink;>
<!ATTLIST a name CDATA #REQUIRED>
<!ELEMENT anchorlink %InlineExceptLink;>
<!ATTLIST anchorlink name CDATA #REQUIRED>
<!ELEMENT sd %InlineExceptLink;>

<!-- Simple block elements -->

<!ELEMENT p %Inline;>
<!ATTLIST p margin (yes|no) "yes">
<!ELEMENT heading %Inline;>
<!ELEMENT pre %Inline;>
<!ELEMENT precode %Inline;>
<!ELEMENT example %InlineOrBlock;>
<!ATTLIST example noheader CDATA #IMPLIED>
<!ELEMENT examples %InlineOrBlock;>
<!ATTLIST examples noheader CDATA #IMPLIED>
<!ELEMENT indent %Block;>

<!-- Fancier block elements -->

<!ELEMENT ul (li|ul)*>
<!ATTLIST ul appearance (normal|compact) "normal">
<!ELEMENT ol (li*)>
<!ELEMENT li %InlineOrBlock;>

<!ELEMENT dl (dt, dd)*>
<!ELEMENT dt %Inline;>
<!ELEMENT dd %Block;>

<!ELEMENT paramlist (param*)>
<!ELEMENT param %Block;>
<!ATTLIST param name CDATA #REQUIRED required (yes|no) "no">

<!ELEMENT flaglist (flag*)>
<!ELEMENT flag %Block;>
<!ATTLIST flag name CDATA #REQUIRED>

<!ELEMENT table (tr*)>
<!ELEMENT tr (th|td)*>
<!ELEMENT th %InlineOrBlock;>
<!ATTLIST th nowrap CDATA #IMPLIED>
<!ELEMENT td %InlineOrBlock;>
<!ATTLIST td nowrap CDATA #IMPLIED>

=== jrsoftware/issrc/isx.xml
<?xml version="1.0" ?>
<!DOCTYPE ishelp SYSTEM "isetup.dtd">

<!--
  Inno Setup
  Copyright (C) 1997-2008 Jordan Russell
  Portions by Martijn Laan
  For conditions of distribution and use, see LICENSE.TXT.
-->

<ishelp version="1">

<!-- Topics -->

<topic name="scriptintro" title="Pascal Scripting: Introduction">
<keyword value="Pascal Scripting: Introduction" />
<body>

<p>The Pascal scripting feature (modern Delphi-like Pascal) adds lots of new possibilities to customize your Setup or Uninstall at run-time. Some examples:</p>

<ul>

<li>Support for aborting Setup or Uninstall startup under custom conditions.</li>

<li>Support for adding custom wizard pages to Setup at run-time.</li>

<li>Support for extracting and calling DLL or other files from the Pascal script before, during or after the installation.</li>

<li>Support for scripted constants that can do anything the normal constants, the read-from-registry, read-from-ini and read-from-commandline constants can do + more.</li>

<li>Support for run-time removal of types, components and/or tasks under custom conditions.</li>

<li>Support for conditional installation of <tt>[Files]</tt>, <tt>[Registry]</tt>, <tt>[Run]</tt> etc. entries based on custom conditions.</li>

<li>Lots of support functions to do from the Pascal script just about everything Inno Setup itself does/can do + more.</li>

</ul>

<p>An integrated run-time debugger to debug your custom Pascal script is also available.</p>

<p>The scripting engine used by Inno Setup is RemObjects Pascal Script by Carlo Kok. Like Inno Setup, RemObjects Pascal Script is freely available and comes with source. See <extlink href="http://www.remobjects.com/ps">http://www.remobjects.com/ps</extlink> for more information.</p>

<p>Note: the Pascal scripting feature works exclusively at run-time, and has no compile-time functionality.</p>

<p><br/><b>See also</b><br/>
<link topic="scriptcreating">Creating the [Code] section</link><br/>
<link topic="scriptevents">Event Functions</link><br/>
<link topic="scriptconstants">Scripted Constants</link><br/>
<link topic="scriptcheck">Check Parameters</link><br/>
<link topic="scriptinstall">BeforeInstall and AfterInstall Parameters</link><br/>
<link topic="scriptuninstall">Uninstall Code</link><br/>
<link topic="scriptexamples">Examples</link><br/>
<link topic="scriptfunctions">Support Functions Reference</link><br/>
<link topic="scriptclasses">Support Classes Reference</link><br/>
<link topic="scriptpages">Using Custom Wizard Pages</link><br/>
<link topic="scriptdll">Using DLLs</link><br/>
<link topic="scriptautomation">Using COM Automation objects</link>
</p>

</body>
</topic>



<topic name="scriptcreating" title="Pascal Scripting: Creating the [Code] Section">
<keyword value="Pascal Scripting: Creating the [Code] Section" />
<keyword value="[Code] section" />
<keyword value="Code" />
<body>

<p>The <tt>[Code]</tt> section is an optional section that specifies a Pascal script. A Pascal script can be used to customize Setup or Uninstall in many ways. Note that creating a Pascal script is not easy and requires experience with Inno Setup and knowledge about programming in Pascal or at least a similar programming language.</p>

<p>The "Code*.iss" and "UninstallCode*.iss" files in the "Examples" subdirectory in your Inno Setup directory contain various example <tt>[Code]</tt> sections. Please study them carefully before trying to create your own Pascal script.</p>

<p>Note: to learn more the Pascal programming language you may find useful to refer to Marco Cantu's free Essential Pascal book. See <extlink href="http://www.marcocantu.com/epascal/">http://www.marcocantu.com/epascal/</extlink>.</p>

</body>
</topic>



<topic name="scriptevents" title="Pascal Scripting: Event Functions">
<keyword value="Pascal Scripting: Event Functions" />
<keyword value="Event Functions" />
<keyword value="InitializeSetup" anchor="InitializeSetup" />
<keyword value="InitializeWizard" anchor="InitializeWizard" />
<keyword value="DeinitializeSetup" anchor="DeinitializeSetup" />
<keyword value="CurStepChanged" anchor="CurStepChanged" />
<keyword value="NextButtonClick" anchor="NextButtonClick" />
<keyword value="BackButtonClick" anchor="BackButtonClick" />
<keyword value="CancelButtonClick" anchor="CancelButtonClick" />
<keyword value="ShouldSkipPage" anchor="ShouldSkipPage" />
<keyword value="CurPageChanged" anchor="CurPageChanged" />
<keyword value="CheckPassword" anchor="CheckPassword" />
<keyword value="NeedRestart" anchor="NeedRestart" />
<keyword value="UpdateReadyMemo" anchor="UpdateReadyMemo" />
<keyword value="RegisterPreviousData" anchor="RegisterPreviousData" />
<keyword value="CheckSerial" anchor="CheckSerial" />
<keyword value="GetCustomSetupExitCode" anchor="GetCustomSetupExitCode" />
<keyword value="PrepareToInstall" anchor="PrepareToInstall" />
<keyword value="RegisterExtraCloseApplicationsResources" anchor="RegisterExtraCloseApplicationsResources" />
<keyword value="InitializeUninstall" anchor="InitializeUninstall" />
<keyword value="DeinitializeUninstall" anchor="DeinitializeUninstall" />
<keyword value="CurUninstallStepChanged" anchor="CurUninstallStepChanged" />
<keyword value="UninstallNeedRestart" anchor="UninstallNeedRestart" />
<keyword value="InitializeUninstallProgressForm" anchor="InitializeUninstallProgressForm" />
<keyword value="ssInstall" anchor="TSetupStep" />
<keyword value="ssPostInstall" anchor="TSetupStep" />
<keyword value="ssDone" anchor="TSetupStep" />
<keyword value="usAppMutexCheck" anchor="TUninstallStep" />
<keyword value="usUninstall" anchor="TUninstallStep" />
<keyword value="usFinished" anchor="TUninstallStep" />
<keyword value="usTerminate" anchor="TUninstallStep" />
<keyword value="wpWelcome" anchor="PageID" />
<keyword value="wpLicense" anchor="PageID" />
<keyword value="wpPassword" anchor="PageID" />
<keyword value="wpInfoBefore" anchor="PageID" />
<keyword value="wpUserInfo" anchor="PageID" />
<keyword value="wpSelectDir" anchor="PageID" />
<keyword value="wpSelectComponents" anchor="PageID" />
<keyword value="wpSelectProgramGroup" anchor="PageID" />
<keyword value="wpSelectTasks" anchor="PageID" />
<keyword value="wpReady" anchor="PageID" />
<keyword value="wpPreparing" anchor="PageID" />
<keyword value="wpInstalling" anchor="PageID" />
<keyword value="wpInfoAfter" anchor="PageID" />
<keyword value="wpFinished" anchor="PageID" />
<body>

<p>The Pascal script can contain several event functions which are called at appropriate times.</p>

<heading>Setup event functions</heading>

<p>Setup supports following event functions:</p>

<dl>

<dt><tt>function <a name="InitializeSetup">InitializeSetup</a>(): Boolean;</tt></dt>
<dd>
<p>Called during Setup's initialization. Return False to abort Setup, True otherwise.</p>
</dd>

<dt><tt>procedure <a name="InitializeWizard">InitializeWizard</a>();</tt></dt>
<dd>
<p>Use this event function to make changes to the wizard or wizard pages at startup. You can't use the <tt>InitializeSetup</tt> event function for this since at the time it is triggered, the wizard form does not yet exist.</p>
</dd>

<dt><tt>procedure <a name="DeinitializeSetup">DeinitializeSetup</a>();</tt></dt>
<dd>
<p>Called just before Setup terminates. Note that this function is called even if the user exits Setup before anything is installed.</p>
</dd>

<dt><tt>procedure <a name="CurStepChanged">CurStepChanged</a>(CurStep: <anchorlink name="TSetupStep">TSetupStep</anchorlink>);</tt></dt>
<dd>
<p>You can use this event function to perform your own pre-install and post-install tasks.</p>
<p>Called with CurStep=ssInstall just before the actual installation starts, with CurStep=ssPostInstall just after the actual installation finishes, and with CurStep=ssDone just before Setup terminates after a successful install.</p>
</dd>

<dt><tt>function <a name="NextButtonClick">NextButtonClick</a>(<anchorlink name="PageID">CurPageID</anchorlink>: Integer): Boolean;</tt></dt>
<dd>
<p>Called when the user clicks the Next button. If you return True, the wizard will move to the next page; if you return False, it will remain on the current page (specified by CurPageID).</p>
<p>Note that this function is called on silent installs as well, even though there is no Next button that the user can click. Setup instead simulates "clicks" on the Next button. On a silent install, if your <tt>NextButtonClick</tt> function returns False prior to installation starting, Setup will exit automatically.</p>
</dd>

<dt><tt>function <a name="BackButtonClick">BackButtonClick</a>(<anchorlink name="PageID">CurPageID</anchorlink>: Integer): Boolean;</tt></dt>
<dd>
<p>Called when the user clicks the Back button. If you return True, the wizard will move to the previous page; if you return False, it will remain on the current page (specified by CurPageID).</p>
</dd>

<dt><tt>procedure <a name="CancelButtonClick">CancelButtonClick</a>(<anchorlink name="PageID">CurPageID</anchorlink>: Integer; var Cancel, Confirm: Boolean);</tt></dt>
<dd>
<p>Called when the user clicks the Cancel button or clicks the window's Close button. The <tt>Cancel</tt> parameter specifies whether normal cancel processing should occur; it defaults to True. The <tt>Confirm</tt> parameter specifies whether an "Exit Setup?" message box should be displayed; it usually defaults to True. If <tt>Cancel</tt> is set to False, then the value of <tt>Confirm</tt> is ignored.</p>
</dd>

<dt><tt>function <a name="ShouldSkipPage">ShouldSkipPage</a>(<anchorlink name="PageID">PageID</anchorlink>: Integer): Boolean;</tt></dt>
<dd>
<p>The wizard calls this event function to determine whether or not a particular page (specified by PageID) should be shown at all. If you return True, the page will be skipped; if you return False, the page may be shown.</p>
