=== jrsoftware/issrc/ISHelp/ispp.dtd
<!ENTITY % highlight "sec|evt|key|com|con|str|num|ispp">

<!ELEMENT yasyx     (topic)*>
<!ELEMENT topic     (title|subtopicstitle|keywords|syntax|description|(topic|section)*)+>
<!ATTLIST topic
  id      ID        #IMPLIED
  unlisted (yes|no) "no"
  usetitle (yes|no) "yes">

<!ELEMENT title     (#PCDATA)*>
<!ELEMENT subtopicstitle     (#PCDATA)*>

<!ELEMENT keywords  (kwd)*>
<!ELEMENT kwd       (#PCDATA)*>

<!ELEMENT description (p|pre|table|ul)*>
<!ATTLIST description 
  header (yes|no)   "yes">

<!ELEMENT section (p|pre|table|ul)*>
<!ATTLIST section
  title  CDATA      #REQUIRED>

<!ELEMENT p         (#PCDATA|tt|i|link|extlink|sd|sn)*>
<!ELEMENT pre       (line)*>
<!ELEMENT line      (#PCDATA|link|b|%highlight;)*>
<!ELEMENT tt        (#PCDATA|i|link|extlink)*>
<!ELEMENT code      (#PCDATA|b|i|link)*>
<!ELEMENT link      (#PCDATA)*>
<!ATTLIST link
  href    CDATA     #IMPLIED
  popup   (yes|no)  "no">
<!ELEMENT extlink   (#PCDATA)*>
<!ATTLIST extlink
  href    CDATA     #REQUIRED>
<!ELEMENT i         (#PCDATA)*>
<!ELEMENT b         (#PCDATA)*>
<!ELEMENT sd        (#PCDATA)*>
<!ELEMENT sn        (#PCDATA)*>

<!ELEMENT sec       (#PCDATA|%highlight;)*>
<!ELEMENT evt       (#PCDATA|%highlight;)*>
<!ELEMENT key       (#PCDATA|%highlight;)*>
<!ELEMENT com       (#PCDATA|%highlight;)*>
<!ELEMENT con       (#PCDATA|%highlight;)*>
<!ELEMENT str       (#PCDATA|%highlight;)*>
<!ELEMENT num       (#PCDATA|%highlight;)*>
<!ELEMENT ispp      (#PCDATA|%highlight;)*>

<!ELEMENT syntax (define)*>

<!ELEMENT define (variant|cases|opt|txt|nt|group)*>
<!ATTLIST define 
  id    ID      #IMPLIED
  inline (yes|no) "no">

<!ELEMENT variant (txt|nt|opt|cases|group)*>
<!ATTLIST variant
  br      (yes|no)  "yes">

<!ELEMENT group (txt|nt|opt|group|cases)*>
<!ATTLIST group
  repeated (yes|no) "no">

<!ELEMENT txt (#PCDATA)>
<!ELEMENT nt (#PCDATA)*>
<!ATTLIST nt
  doc    CDATA #IMPLIED
  name   CDATA #IMPLIED>
<!ELEMENT opt (txt|nt|opt|group)*>
<!ATTLIST opt
  repeated (yes|no) "no">

<!ELEMENT cases (case)+>
<!ATTLIST cases
  repeated (yes|no) "no">

<!ELEMENT case (txt|nt|opt|cases)*>

<!ELEMENT table       (tr)*>
<!ELEMENT tr          (th|td)*>
<!ELEMENT th          (#PCDATA)>
<!ATTLIST th
  nowrap CDATA #IMPLIED>
<!ELEMENT td          (#PCDATA|b|i|link|extlink|table|code)*>
<!ATTLIST td
  nowrap CDATA #IMPLIED>

<!ELEMENT ul          (li)*>
<!ELEMENT li          (#PCDATA|tt|link|extlink|p|pre)*>

=== jrsoftware/issrc/ISHelp/ispp.xml
<?xml version="1.0"?>
<!DOCTYPE yasyx SYSTEM "ispp.dtd" [
 <!ENTITY sp      "&#160;">
 <!ENTITY dsp     "&#160;&#160;">
 <!ENTITY define  '<tt><link href="define">define</link></tt>'>
 <!ENTITY undef   '<tt><link href="undef">undef</link></tt>'>
 <!ENTITY dim     '<tt><link href="dim">dim</link></tt>'>
 <!ENTITY redim   '<tt><link href="dim">redim</link></tt>'>
 <!ENTITY emit    '<tt><link href="emit">emit</link></tt>'>
 <!ENTITY error   '<tt><link href="error">error</link></tt>'>
 <!ENTITY include '<tt><link href="include">include</link></tt>'>
 <!ENTITY insert  '<tt><link href="insert">insert</link></tt>'>
 <!ENTITY pragma  '<tt><link href="pragma">pragma</link></tt>'>
 <!ENTITY file    '<tt><link href="file">file</link></tt>'>
 <!ENTITY ifdef   '<tt><link href="ifdef">ifdef</link></tt>'>
 <!ENTITY ifndef  '<tt><link href="ifdef">ifndef</link></tt>'>
 <!ENTITY ifexist '<tt><link href="ifdef">ifexist</link></tt>'>
 <!ENTITY ifnexist '<tt><link href="ifdef">ifnexist</link></tt>'>
 <!ENTITY if      '<tt><link href="if">if</link></tt>'>
 <!ENTITY elif    '<tt><link href="if">elif</link></tt>'>
 <!ENTITY else    '<tt><link href="if">else</link></tt>'>
 <!ENTITY endif   '<tt><link href="if">endif</link></tt>'>
 <!ENTITY sub     '<tt><link href="sub">sub</link></tt>'>
 <!ENTITY endsub  '<tt><link href="sub">endsub</link></tt>'>
 <!ENTITY for     '<tt><link href="for">for</link></tt>'>
 <!ENTITY env     '<tt><link href="env">env</link></tt>'>
 <!ENTITY expr    '<tt>expr</tt>'> <!-- not a directive -->
 <!ENTITY curtrans '<link href="current-translation">current preprocessor output</link>'>
 <!ENTITY translation '<link href="translation">preprocessor output</link>'>
 <!ENTITY builtins '<link href="builtinsiss">ISPPBuiltins.iss</link>'>
 <!ENTITY dash "&#8211;">
]>
<yasyx>
	<topic id="isppoverview">
		<title>Introduction</title>
		<description header="no">
			<p>The main purpose of Inno Setup Preprocessor (ISPP) is to automate compile-time tasks and avoid repetition in your scripts. For example, you can declare a compile-time preprocessor variable &dash; containing your application name, for instance &dash; and then use its value in several places of your script. If for some reason you need to change the name of your application, you'll have to change it only once in your script. Without the preprocessor, you would need to change all occurrences of your application name throughout the script.</p>
			<p>Another example of using the preprocessor would be gathering version information from your application at compile-time by reading the version info of an EXE file, and using it in your <link href="setup_appvername">AppVerName</link> [Setup] section directive or anywhere else. Without the preprocessor, you would have to modify your script each time the version of your application changes.</p>
			<p>The preprocessor can even scan your source folder and generate script lines for the found files. Without the preprocessor, you would have to manually maintain the list of files.</p>
			<p>Conditional in- and exclusion of portions of script is also possible by using the preprocessor: you can create one single script for different versions/levels of your applications (for example, trial versus fully functional). Without the preprocessor, you would need multiple scripts.</p>
			<p>Finally, the preprocessor makes it possible to split long lines using a line spanning symbol.</p>
			<p>Note: the preprocessor works exclusively at compile-time, and has no run-time functionality.</p>
    </description>
		<subtopicstitle>All topics</subtopicstitle>
		<topic id="directives">
			<title>Directives Reference</title>
 			<description header="no">
				<p>There are two kinds of directives in ISPP: simple and inline.</p>
				<p>Simple directives occupy a whole line and begin with the <tt>#</tt> symbol. For example the following defines a variable called <tt>MyAppName</tt>:</p>
				<pre>
					<line>#define MyAppName "My Program"</line>
				</pre>
				<p>Inline directives appear inside other lines and begin with <tt>{#</tt> and end with <tt>}</tt>. For example the following sets Inno Setup's <tt>AppName</tt> directive to the value of the previously defined variable:</p>
				<pre>
					<line>[Setup]</line>
					<line>AppName={#MyAppName}</line>
				</pre>
				<p>As seen in the above example it is not necessary to specify the name of the &emit; directive when it is used inline, so <tt>{#MyAppName}</tt> is short for <tt>{#emit MyAppName}</tt>.</p>
			</description>
			<section title="Directive syntax documenting conventions">
				<p>Directive usage syntax uses the following conventions.</p>
				<table>
					<tr><td><code>()</code></td><td>Group of tokens.</td></tr>
					<tr><td><code>[]</code></td><td>Optional token or group of tokens.</td></tr>
					<tr><td><code>|</code></td><td>Mutually exclusive tokens.</td></tr>
					<tr><td><code>...</code></td><td>Previous token or group of tokens can be repeated.</td></tr>
					<tr><td><code><b>token</b></code></td><td>Reserved word or symbol(s). Must be typed exactly as shown.</td></tr>
					<tr><td><code>&lt;token&gt;</code></td><td>Non-terminal. Its syntax is either shown before, or explained.</td></tr>
				</table>
			</section>
			<subtopicstitle>Available directives</subtopicstitle>
			<topic id="define">
				<title>#define</title>
				<keywords>
          <kwd>#:</kwd>
          <kwd>define</kwd>
        </keywords>
				<syntax>
					<define id="define-directive">
						<variant><nt name="variable-definition"/></variant>
						<variant><nt name="macro-definition"/></variant>
						<variant><nt name="default-visibility-set"/></variant>
					</define>
					<define id="variable-definition">
						<group><nt name="define-dir-name"/></group><opt><nt name="locality"/></opt><nt>ident</nt><opt><nt name="index-spec"/></opt><opt><opt><txt>=</txt></opt><nt>expr</nt></opt>
					</define>
					<define id="macro-definition">
						<group><nt name="define-dir-name"/></group><opt><nt name="locality"/></opt><nt>ident</nt><txt>(</txt><opt><nt name="formal-macro-args"/></opt><txt>)</txt><nt>expr</nt>
					</define>
					<define id="default-visibility-set">
						<group><nt name="define-dir-name"/></group><nt name="locality"/>
					</define>
					<define id="define-dir-name" inline="yes">
						<cases>
							<case><txt>define</txt></case>
							<case><txt>:</txt></case>
						</cases>
					</define>
					<define id="formal-macro-args">
						<nt name="formal-macro-arg"/><opt repeated="yes"><txt>,</txt><nt name="formal-macro-arg"/></opt>
					</define>
					<define id="formal-macro-arg">
						<cases>
							<case><nt name="by-val-arg"/></case>
							<case><nt name="by-ref-arg"/></case>
						</cases>
					</define>
					<define id="by-val-arg">
						<opt><nt name="type-id"/></opt><nt>ident</nt><opt><txt>=</txt><nt>expr</nt></opt>
					</define>
					<define id="by-ref-arg">
						<opt><nt name="type-id"/></opt><txt>*</txt><nt>ident</nt>
					</define>
					<define id="type-id">
						<cases>
							<case><txt>any</txt></case>
							<case><txt>int</txt></case>
							<case><txt>str</txt></case>
							<case><txt>func</txt></case>
						</cases>
					</define>
					<define id="locality" inline="yes">
						<cases>
							<case><txt>private</txt></case>
							<case><txt>protected</txt></case>
							<case><txt>public</txt></case>
						</cases>
					</define>
				</syntax>
				<description>
					<p>The first syntax ("variable-definition") defines a variable named <tt>ident</tt>, or assigns a value to an element of an array named <tt>ident</tt> (use &dim; instead of <tt>define</tt> to define the array variable itself). If none of the <tt>public</tt>, <tt>protected</tt>, or <tt>private</tt> keywords are specified, default <link href="visibility">visibility</link> is assumed.</p>
					<p>The second syntax ("macro-definition") defines <link href="macros">a user defined function</link> named <tt>ident</tt>. When defining a user defined function there must be no whitespace between the name and opening parenthesis, otherwise it will be treated as variable declaration.</p>
					<p>The third syntax ("default-visibility-set") sets the default <link href="visibility">visibility</link> of further variable and user defined function definitions in this file. If no visibility declaration occurs in a file, public visibility is assumed by default.</p>
				</description>
				<section title="Examples">
					<pre>
						<line>#define MyAppName "My Program"</line>
						<line>#define MyAppExe MyAppName + ".exe"</line>
						<line>#define MyAppVer <link href="GetVersionNumbersString">GetVersionNumbersString</link>(MyAppExe)</line>
						<line>#define MyArray[0] 15</line>
						<line>#define Multiply(int A, int B = 10) A * B</line>
					</pre>
				</section>
				<section title="See also">
					<p>&dim;, &undef;, <link href="visibility"/>.</p>
					<p><link href="macros"/>.</p>
				</section>
			</topic>
			<topic id="dim">
				<title>#dim, #redim</title>
				<keywords>
          <kwd>dim</kwd>
          <kwd>#redim</kwd>
          <kwd>redim</kwd>
        </keywords>
				<syntax>
					<define id="dim-directive">
						<txt>dim</txt><opt><nt name="locality"/></opt><nt>ident</nt><nt name="index-spec"/><opt><nt name="initializers-spec"/></opt>
					</define>
					<define id="redim-directive">
						<txt>redim</txt><opt><nt name="locality"/></opt><nt>ident</nt><nt name="index-spec"/>
					</define>
					<define id="index-spec" inline="yes">
						<txt>[</txt><nt>expr</nt><txt>]</txt>
					</define>
					<define id="initializers-spec" inline="yes">
						<txt>{</txt><nt>expr</nt><opt repeated="yes"><txt>,</txt><nt>expr</nt></opt><txt>}</txt>
					</define>
				</syntax>
				<description>
